spring:
  application:
    name: island-mall
  profiles:
    active: dev
server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/org/chenzx/island/mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  signature-key: 12341241251
  access-token-expiration-time: 1
  refresh-token-expiration-time: 3

security:
  default-avatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif


