spring:
  application:
    name: island-mall
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_EMPTY
server:
  port: 8080
  servlet:
    context-path: /island

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/org/chenzx/island/mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

user:
  default-avatar: https://wpimg.wallstcn.com/f778738c-e4f8-4870-b634-56703b4acafe.gif

jwt:
  signature-key: 12341241251
  access-token-expiration-time: 1
  refresh-token-expiration-time: 3

security:
  exclude-url:
    - /sys/auth/login
    - /sys/auth/logout
    - /sys/auth/refreshToken
    - /sys/auth/register

swagger:
  enabled: true
